/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./frontend/screens/*.html",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#bac3ff",
        "on-primary": "#00208e",
        "primary-container": "#1a3fd4",
        "on-primary-container": "#bac3ff",
        "primary-fixed": "#dee0ff",
        "primary-fixed-dim": "#bac3ff",
        secondary: "#a2c9ff",
        "on-secondary": "#00315c",
        "secondary-container": "#0071c7",
        "secondary-fixed": "#d3e4ff",
        "secondary-fixed-dim": "#a2c9ff",
        tertiary: "#ffb5a0",
        "on-tertiary": "#601400",
        "tertiary-container": "#9c2700",
        "tertiary-fixed": "#ffdbd1",
        "tertiary-fixed-dim": "#ffb5a0",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        background: "#12131b",
        "on-background": "#e2e1ed",
        surface: "#12131b",
        "surface-dim": "#12131b",
        "surface-bright": "#383942",
        "surface-container-lowest": "#0c0e16",
        "surface-container-low": "#1a1b24",
        "surface-container": "#1e1f28",
        "surface-container-high": "#282932",
        "surface-container-highest": "#33343d",
        "surface-variant": "#33343d",
        "on-surface": "#e2e1ed",
        "on-surface-variant": "#c4c5d8",
        outline: "#8e8fa1",
        "outline-variant": "#444655",
        "inverse-surface": "#e2e1ed",
        "inverse-on-surface": "#2f3039",
        "inverse-primary": "#2d4de0",
        "on-secondary-container": "#f0f4ff",
        "on-secondary-fixed": "#001c38",
        "on-secondary-fixed-variant": "#004882",
        "on-tertiary-container": "#ffb4a0",
        "on-tertiary-fixed": "#3b0900",
        "on-tertiary-fixed-variant": "#872100",
        "surface-tint": "#bac3ff",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "code-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      spacing: {
        "container-max-width": "1440px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
